name: Run Tests

on:
    push:
        branches:
            - main
    pull_request:

concurrency:
    group: tests-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node-version: [18.x, 20.x]

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: '0'

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  cache: 'npm'
                  node-version: ${{ matrix.node-version }}

            - run: npm ci
            - run: npm run build
            - run: npm run test
